---
title: "2024 metų Seimo rinkimų eigos analizė"
format: 
    html:
        embed-resources: true
        code-fold: true
        df-print: paged
        toc: true
        toc-location: left
        theme: cosmo
knitr: 
  opts_chunk: 
    echo: false
    message: false
    warning: false

---

## Apylinkių skaičius

Iš viso yra 1947 apylinkės

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)

dt <- read.csv("data/20241013/daugmvrt.csv") %>% 
    mutate(timestamp = ymd_hms(timestamp)) %>% filter(timestamp>= ymd_hms("2024-10-13 21:00:00"))

ap <- dt %>%
    select(timestamp, apylinkes, lt_proc_rinkeju) %>%
    unique()

san <- readxl::read_xlsx("data/santrumpos.xlsx")

dt1 <- dt %>% left_join(san)

ggplot(aes(x = timestamp, y = apylinkes), data = ap) +
    geom_col() +
    theme_bw() +
    labs(x = "Laikas", y = "Apylinkės", title = "Apylinkių pristačiusių duomenis skaičius")
```
```{r}
ggplot(aes(x = timestamp, y = lt_proc_rinkeju), data = ap) +
    geom_col() +
    theme_bw() +
    labs(x = "Laikas", y = "Apylinkės", title = "Suskaičiuotų balsų procentas")
```


## Balsavimo rezultatai

### 7 partijos

```{r}
top7 <- c(3, 12,13,8,11,14,16)
cols <- RColorBrewer::brewer.pal(7, "Set1")

dt2 <- dt1 %>% filter(saraso_numeris %in% top7)

mt <- dt2 %>% select(saraso_numeris, santrumpa, spalva) %>% unique %>% arrange(saraso_numeris)

dt3 <- dt2 %>% mutate(santrumpa = factor(santrumpa, levels = mt$santrumpa))

ggplot(aes(x = timestamp, y = proc_nuo_dal_rinkeju, group = santrumpa, colour = santrumpa), data = dt3) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mt$spalva) +
    labs(x = "Laikas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Balsavimo rezultatų kitimas laike")
```

### 7 partijos x ašis kita

```{r}
top7 <- c(3, 12,13,8,11,14,16)
cols <- RColorBrewer::brewer.pal(7, "Set1")

dt2 <- dt1 %>% filter(saraso_numeris %in% top7)

mt <- dt2 %>% select(saraso_numeris, santrumpa, spalva) %>% unique %>% arrange(saraso_numeris)

dt3 <- dt2 %>% mutate(santrumpa = factor(santrumpa, levels = mt$santrumpa))

ggplot(aes(x = lt_proc_rinkeju, y = proc_nuo_dal_rinkeju, group = santrumpa, colour = santrumpa), data = dt3) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mt$spalva) +
    labs(x = "Suskaičiuotų balsų procentas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Balsavimo rezultatų kitimas laike")
```



### 7 partijos mažiau 10 procentų

```{r}

dt4 <- dt3 %>% filter(proc_nuo_dal_rinkeju<10 & proc_nuo_dal_rinkeju>5)
mt4 <- mt %>% filter(spalva %in% unique(dt4$spalva))

ggplot(aes(x = lt_proc_rinkeju, y = proc_nuo_dal_rinkeju, group = santrumpa, colour = santrumpa), data = dt4) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mt4$spalva) +
    labs(x = "Laikas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Procentas nuo dalyvavusių rinkėjų")
```

### Tiesinių prognozių kitimas

Su kiekvienu duomenų atnaujinimu padaroma prognozė pagal turimus trendus, koks bus galutinis rezultatas.

```{r}
do_one_forecast <- function(dt, sno) {
    vv <- dt %>% filter(saraso_numeris == sno) %>% arrange(timestamp)
    rr <- 6:nrow(vv)
    fc <- sapply(rr, function(x) {
        mod <- lm(proc_nuo_dal_rinkeju~lt_proc_rinkeju, data = vv[1:x,])
        res <- predict(mod, newdata = data.frame(lt_proc_rinkeju = 100))
        as.numeric(res)
    })
    data.frame(saraso_numeris =sno, 
               lt_proc_rinkeju = vv$lt_proc_rinkeju[rr], 
               timestamp = vv$timestamp[rr], forecast = fc) 
    
}

fc <- lapply(unique(as.integer(dt1$saraso_numeris)), function(x)do_one_forecast(dt1,x)) %>% bind_rows

fc1 <- fc %>% left_join(dt1 %>% select(saraso_numeris, santrumpa, spalva) %>% unique)

fc2 <- fc1 %>% filter(saraso_numeris %in% top7)

mt <-  fc2 %>% select(saraso_numeris, santrumpa, spalva) %>% unique %>% arrange(saraso_numeris)

fc3 <- fc2 %>% mutate(santrumpa = factor(santrumpa, levels = mt$santrumpa))

ggplot(aes(x = lt_proc_rinkeju, y = forecast, group = santrumpa, colour = santrumpa), data = fc3) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mt$spalva) +
    labs(x = "Suskaičiuotų balsų procentas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Momentinė galutinio rinkimų rezultatų prognozė")

```

```{r}
library(knitr)
ll <- fc1 %>% filter(timestamp == max(timestamp))

ll1 <- ll %>% arrange(forecast) %>% select(santrumpa, prognoze = forecast) %>% 
    mutate(prognoze = round(prognoze, 1)) %>% arrange(-prognoze)

kable(ll1)
```

### Žemiau 5 procentų

```{r}


dtg <- dt1 %>% filter(proc_nuo_dal_rinkeju<5)
mtg <- dtg %>% select(saraso_numeris, santrumpa, spalva) %>% unique %>% arrange(saraso_numeris)

dtg1 <- dtg %>% mutate(santrumpa = factor(santrumpa, levels = mtg$santrumpa))

ggplot(aes(x = timestamp, y = proc_nuo_dal_rinkeju, group = santrumpa, colour = santrumpa), data = dtg1) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mtg$spalva) +
    labs(x = "Laikas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Balsavimo rezultatų kitimas laike")
```

### Įdomesni trendai

```{r}

ggplot(aes(x = timestamp, y = proc_nuo_dal_rinkeju, group = santrumpa, colour = santrumpa), data = dtg1 %>% filter(saraso_numeris %in% c(16,5, 2))) +
    geom_point() +
    geom_line() +
    theme_bw() +
    scale_colour_manual(name = "Partija", values = mtg %>% filter(saraso_numeris %in% c(16,5, 2)) %>% .$spalva) +
    labs(x = "Laikas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Balsavimo rezultatų kitimas laike")
```

### Kaimynų projektų sėkmė

```{r}

dtk <- dt1 %>% group_by(timestamp, kaimynai) %>% summarise(proc_nuo_dal_rinkeju = sum(proc_nuo_dal_rinkeju)) %>% 
    mutate(kaimynai = as.character(kaimynai))

ggplot(aes(x = timestamp, y = proc_nuo_dal_rinkeju), data = dtk %>% filter(kaimynai == 1))  +
    geom_point() +
    geom_line() +
    theme_bw() +
   # scale_color_discrete(name = "Projektas")+
    #scale_colour_manual(name = "Partija", values = mtg %>% filter(saraso_numeris %in% c(16,2)) %>% .$spalva) +
    labs(x = "Laikas", y = "Procentas nuo dalyvavusių rinkėjų", title = "Balsavimo rezultatų kitimas laike")
```